name: Retrieve secret
on:
  push:
    branches: [ main ]
jobs:
  decode-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Encode secret into a file
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo $TEST_SECRET | base64 -encode > cert.der
      - name: Show encoded secret
        run: cat cert.der
