name: Retrieve secret
on:
  push:
    branches: [ main ]
jobs:
  decode-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve the secret and decode it to a file
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo $TEST_SECRET | base64 --decode > cert.der
      - name: Show certificate information
        run: cat cert.der
