name: Retrieve secret
on:
  push:
    branches: [ main ]
jobs:
  decode-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decode secret into a file
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          x=$(echo ${"TEST_SECRET"} | base64)
          echo $x
